### ISSUE TITLE
No docker image found for v2.1.0 release

### ISSUE THREAD

**Issue by apoorva-marisomaradhya** [camptocamp/terraboard#229]
Looks like there's no docker image for release v2.1.0. We would like to get on the latest version, if you could make the docker image available for v2.1.0.

**Comment by hbollon** [comment]
Hey @apoorva-marisomaradhya !
Sorry for the omission, it's fixed!
I'll try to include this in the continuous deployment workflow so it doesn't happen again for future releases. :smile: 
Have fun with the new version!

**Comment by apoorva-marisomaradhya** [comment]
Hey, looks like something off with the tag. I updated to v2.1.0 but in the UI I see [Terraboard v2.0.0-alpha.2-21-ge7d2923]

**Comment by hbollon** [comment]
Seems to be an issue regarding `git describe` command which ignore non-annotated tags by default (tags were previously annotated but since our tags/releases are managed by `release-please` this is no longer the case).
The Docker image `v2.1.0` or `latest` are indeed based on version 2.1.0 but I will fix this UI issue ASAP :+1:
